$script = <<SCRIPT

timedatectl set-timezone Asia/Taipei
timedatectl set-ntp on
export DEBIAN_FRONTEND=noninteractive

# install apache2+php7.0
apt-get update
apt-get install -y python-software-properties
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install -y build-essential curl git unzip php-pear php-dev libcurl4-openssl-dev vim apache2 libapache2-mod-php7.0
apt-get install -y php7.0 php7.0-mysql php7.0-fpm php7.0-cli php7.0-common php7.0-curl php7.0-gd php7.0-intl php7.0-json php7.0-mbstring 
apt-get install -y php7.0-mcrypt php7.0-opcache php7.0-pgsql php7.0-soap php7.0-sqlite3 php7.0-xml php7.0-xmlrpc php7.0-xsl php7.0-zip php-mongodb php-xdebug

pecl install xdebug
pecl install mongodb

# install mongodb3.2
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
apt-get update
apt-get install -y mongodb-org=3.2.13 mongodb-org-server=3.2.13 mongodb-org-shell=3.2.13 mongodb-org-mongos=3.2.13 mongodb-org-tools=3.2.13

# php.ini setting
echo "extension=mongodb.so" >> /etc/php/7.0/fpm/php.ini
echo "extension=xdebug.so" >> /etc/php/7.0/fpm/php.ini

# exclude from something unnecessary bug
apt-get purge -y php7.1-*

# install composer
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# enable PHP module
phpenmod mcrypt

#clean apt-get 
apt-get autoclean && apt-get -y autoremove


service php7.0-fpm restart
service mongod start
service apache2 restart

SCRIPT



Vagrant.configure(2) do |config|
  config.vm.define :app do |web_config|
    web_config.vm.box = "ubuntu/xenial64"
    web_config.vm.host_name = "web"

    web_config.vm.synced_folder ".", "/vagrant/", type: "nfs"
    web_config.vm.synced_folder "project", "/home/vagrant/project", type: "nfs"
    web_config.vm.network "private_network", ip: "33.33.33.98"
	  web_config.vm.provision "shell", inline: $script

    web_config.vm.provider "virtualbox" do |v|
      v.memory = 1024
    end
  end
end
